# Generated by Django 4.1.2 on 2022-11-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_video_id"),
        ("playlists", "0002_playlist_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="playlist_item", to="videos.video"
            ),
        ),
    ]
