# Generated by Django 4.1.2 on 2022-11-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_alter_video_video_id"),
        ("playlists", "0005_remove_playlist_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True,
                related_name="playlist_item",
                through="playlists.PlaylistItem",
                to="videos.video",
            ),
        ),
    ]
