# Generated by Django 4.1.2 on 2022-11-03 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0006_playlist_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playlists.playlist",
            ),
        ),
    ]
