# Generated by Django 4.1.2 on 2022-11-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0009_playlist_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieProxy",
            fields=[],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playlists.playlist",),
        ),
    ]
