# Generated by Django 4.1.3 on 2022-11-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0011_playlist_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="playlists.playlist",
            ),
        ),
    ]
