# Generated by Django 4.1.2 on 2022-11-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video_id",
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
